[tool.bumpversion]
current_version = "2026.05.11"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "MicroGrowth/VERSION"
